language: java

jdk:
- oraclejdk8

sudo: false

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"

env:
  global:
  - GH_REF: github.com:MrAsimov/architecture-styles-patterns.git
  - secure: SpZZnoUCIgygrZtk2eTNm8UbruHyHt65OMIZczwBGBZOxqyu1IylycojmGAEGOu378HU6nukcyPpErIGCPsCuePo1dt2geEHMHhotRtMtdCWs2kmMdm/V5eAHC1P33XBJyUoVd3KSzXvtzY8MibvRpxLk3jgXU6xoU5FtTHUgL3/2DFdUMqo1X7tY/YALDG4eCjw0TLdJ0Rz55NL3uR+tjtyL27l9mm3NfFbNHT+u+NEH3MwjYZWiKdV5qVfU1hMRbA6nZEp+JWWiSNog0bCH3QyoI3VU380izkq4gjMGnG6WWAdQe9CFSut3ZtvR9aaswSGK4wFxIqlwwksYIjLDxsWh+kjd7pS950sS3up10Z2N+phvHioi1h6wpvfR6BegPqYJL0YGZcFn9G3XsQ9kk01idwU1rZ5StEAlKP1TfdquzQCHTAcnvakXMjUo2skBQ9zDgePgCHxOPRjDKTr+zSfPi9X9vApVSeGKmEV1QSW7Jjw+Qj3fR9DSMeMfRN7OOkpq9ucx0ZplmvW6Y+qAe7sFA5n+XeerJhRyLUKgNWIKSczuWkBp18RNkk3BTu86OoFKG/CBNU+lKzG7HcIZUqhaA9ACWkluNAVMmlGaMLL5P1ywLEvXNE+XNc6hz2cn9wc/Uw9d4Oaxf6xSd/7h0SJxc7ig7pf4SRG6al881E=

install:
- mvn clean install

addons:
  apt:
    packages:
    - oracle-java8-installer
  sonarcloud:
    organization: mrasimov-github
    token:
      secure: PJ15ATN6dYpLPdDV7GAuRE8xIqx8Ki4t+CbfQ3ZF7clFzGAnzmfewKMeTQQdxA8RmFRe+PzaxREhkQTlcuvSlo1UvgV/F9roU7gab3vyLlehx6/ohLA0XszzvYflScWxSXGUTRGDs6XpQ1yitn3ON4Lxua5YI2y0Xr/XB8GmD9pbsVrANT5hE6DRAyTPdfOhXgEWHTtZWA7dL+qOQgod+MMo5q16kGqoAJLcklDveLm/WLDZtTrswV96IFPD34oTOTjcuRHrc+wOlA/+1FZ02IwKF58nyTdn2icikrcCFFB3pp6UOit1PNCTaF99+CoIjxV7eUDpod7IDL+mHsBtnkwk6le36vcHeBbrIKoMnq+Cnx7qPyich4alS+F2YMIiUazM0TlAoc9wkfxTYw/2GzSG+h7vlNI3MkquQ25QOSnTmWMNHaQKEs35voXkMp6QLuxyXEwRii+DMOWDdtaphWIC1GDdUV3daahidyRS007P8LNIEUYSqAWqSGjOniwIeFy5mMfQOW+51gV6cI8yYttFLXAT90+glRMgdQn8sQshl+NtTwqNSjkgJys9VRUupam9cMIxPIz0ZMU7OfrL+ggnmEni/ZdTolXyniqy5NjTGi0nrf7z0g4FEP9RH8rvwX5E/G61MoVgPcAFu2vOKuGFV3jE08UgAduWbXcPmj4=
      branches:
        - master

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
